services:

  eureka-discovery-service:
    build:
      context: ./eureka-discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      tic-network:
        ipv4_address: 172.25.0.3
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-gateway-service:
    build:
      context: ./spring-gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      eureka-discovery-service:
        condition: service_healthy
    networks:
      tic-network:
        ipv4_address: 172.25.0.2

  administration-service:
    build:
      context: ./administration-service
      dockerfile: Dockerfile
    depends_on:
      eureka-discovery-service:
        condition: service_healthy
    networks:
     - tic-network

networks:
  tic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24